name: Scrap ECL Tender Data
description: This workflow runs a Node.js script to scrape ECL tender data daily.

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:  # Optional: allows manual triggering from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or whatever version you use

      - name: Install dependencies
        run: npm install  # or skip if not needed

      - name: Run ecl-tender-scrapper.js
        env:
            TOKEN: ${{ secrets.TOKEN }}
            GIST_ID: ${{ secrets.GIST_ID }}
        run: node scrappers/ecl-tender-scrapper.js
