name: Scrap WB Tender Data
description: This workflow runs a Node.js script to scrape WB tender data daily.

on:
  schedule:
    # Runs every day at 8:00 AM UTC
    - cron: '13 20 * * *'
  workflow_dispatch:  # Optional: allows manual triggering from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # or whatever version you use

      - name: Install dependencies
        run: npm install  # or skip if not needed

      - name: Run script.js
        run: node script.js
